### PR TITLE
Use SPARQL Repository from RDF.rb

### PR DESCRIPTION
**Pull request by terrellt**
This leverages the work done by the core gem for sparql repository interactions
and fixes a few specs and efficiency issues related to querying.

### CODE REVIEW

**Comment by gkellogg** [comment]
The SPARQL::Client::Repository specs are dependent on Dydra, which really makes them pretty useless for normal development due to the turn-around. Perhaps someone would consider binding rdf-marmotta in with a local installation that could run through all the specs locally. For bonus points, get this to install on Travis (similar to how rdf-raptor installs raptor for running tests on Travis) to be able to regular integration testing.

**Comment by anarchivist** [comment]
Hi @gkellogg: `rdf-marmotta` relies on [`jettywrapper`](https://github.com/projecthydra/jettywrapper) and [`marmotta-jetty`](https://github.com/dpla/marmotta-jetty) for integration testing.

**Comment by no-reply** [comment]
@gkellogg thanks for that info.  I've had some trouble using the `rdf-spec` tests in a couple of contexts, mostly (if I recall) because they are pinned to an older version of `rspec` I've been interested in updating them, and wonder if that's a project you'd consider worth undertaking.

Mainly, I want to add a suite of custom matchers for use with `ActiveTriples` and similar projects.

**Comment by gkellogg** [comment]
@anarchivist Noted. Thinking about it, I believe we can do this using RSpec::Rake on a trivial SPARQL gem endpoint, which would be simpler.

@no-reply rdf-spec has a ~> 3.0 dependency on Spec, which should allow it to work with rspec-3.2.0, so I'm not sure what issues you may be having with rdf-spec. I don't have much time to dive into another project, but if you can add issues to rdf-spec, this would allow them to be addressed; particularly if you have simple example behavior that could be used to create new tests against rdf-spec itself.

**Comment by no-reply** [comment]
Yeah, I was proposing to take it on myself.  It's been a while since I've tried to use it, so I'll find time to jump back in and open issues for anything I turn up.

**Comment by gkellogg** [comment]
There's a bit of work to do to support SPARQL 1.1 Update in the sparql gem, but shouldn't be too awefully difficult, just time consuming. See https://github.com/ruby-rdf/sparql-client/issues/58 and https://github.com/ruby-rdf/sparql/issues/18.

**Pull request merged**
